/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

//user@debian:~/Euler$ time ./euler_12 
//76576500
//
//real	0m0.323s
//user	0m0.320s
//sys	0m0.000s

#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include "primelib.c"

uint32_t numdivisors(uint32_t tnum){
	uint32_t mprimes, loop, curfcts, fctc = 1;
	
	//this means we miss 1 or two (two probably?) factors on occasion but works in this case
	mprimes = genprimeto(sqrt(tnum));
	//mprimes = genprimeto(tnum); //counts all but takes a lot longer

	for(loop = 0; loop <= mprimes; loop++){
		curfcts = 1;
		while(!(tnum % primevals[loop])){
			tnum /= primevals[loop];
			curfcts++;
		}
		fctc *= curfcts;
		if(tnum == 1)
			break;
	}
	
	return fctc;
}

int main(void){
	uint32_t curnat = 10, curtr = 45;

	initprime();

	while(1){
		if(numdivisors(curtr) > 500)
			break;
		curtr += curnat++;
	}

	printf("%d\n", curtr);
	return 0;
}
